description: >
  OpenJDK executor to execute SonarScanner.
docker:
  - image: 'cimg/openjdk:<< parameters.tag >>'
parameters:
  tag:
    type: string
    default: 11.0.16
    description: >
      Pick a specific cimg/openjdk image variant:
      https://hub.docker.com/r/cimg/openjdk/tags
